{
 "title": "NEW: Locust Load Test (MockServer)",
 "description": "Обновленный собственный дашборд",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Total RPS",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "locust_requests_current_rps{name=\"Aggregated\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "locust_users", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(locust_requests_num_requests{name=\"Aggregated\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Failures",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(locust_requests_num_failures)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS by endpoint",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "locust_requests_current_rps{name!=\"Aggregated\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Response Time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "locust_requests_median_response_time{name!=\"Aggregated\"}",
     "legendFormat": "median {{name}}"
    },
    {
     "expr": "locust_requests_max_response_time{name!=\"Aggregated\"}",
     "legendFormat": "max {{name}}"
    }
   ]
  }
 ]
}